name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo components
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: Rust Format
        run: cargo fmt --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  build:
    strategy:
      matrix:
        build:
          - type: linux
            os: ubuntu-latest
    runs-on: ${{matrix.build.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: .ci/build.sh
      - name: Run tests
        run: .ci/test.sh
